# ASF is a C# project with solution named ArchiSteamFarm.sln
language: csharp
solution: ArchiSteamFarm.sln

# Save bandwidth by limiting git clone to only last 10 commits
git:
  depth: 10

# Don't build other branches than master
# Sadly Travis doesn't support AppVeyor's "skip_branch_with_pr"
branches:
  only:
    - master

# This is .NET Core project, we're not building with Mono
mono: none

# ASF requires .NET Core 2.0+
# TODO: We should target stable 2.0.0 once it's released
dotnet: 2.0.0-preview2-006497

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

script:
  - dotnet restore
  - dotnet build -c Release

# This is our main build matrix
matrix:
# We can use fast finish, as we don't need to wait for all builds to mark it as failed/passed
  fast_finish: true
  include:
#   We're building ASF with dotnet on latest versions of Linux and OS X
#   Ref: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
    - os: linux
      dist: trusty
      sudo: false
#    - os: osx
#      osx_image: xcode8.3
