version: 1.0.{build}-{branch}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 10
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: out\ASF.exe
  name: ASF.exe
- path: out\ASF-ConfigGenerator.exe
  name: ASF-ConfigGenerator.exe
- path: out\ASF-GUI.exe
  name: ASF-GUI.exe
- path: out\ASF-Service.exe
  name: ASF-Service.exe
- path: out\config\ASF.json
  name: config\ASF.json
- path: out\config\example.json
  name: config\example.json
- path: out\config\minimal.json
  name: config\minimal.json
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/6cc89e76555ee263cc11
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
