version: 1.0.{build}-{branch}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 10
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/6cc89e76555ee263cc11
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
