version: '{build}-{branch}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017 Preview
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
configuration: Release
platform: Any CPU
clone_depth: 10
before_build:
- dotnet restore
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal
