version: '{build}-{branch}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
clone_depth: 10
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
- cmd: dotnet restore
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    dotnet publish -c %CONFIGURATION% -o out\generic

    dotnet publish -c %CONFIGURATION% -r win-x64 -o out\win-x64

    dotnet publish -c %CONFIGURATION% -r linux-x64 -o out\linux-x64

    dotnet publish -c %CONFIGURATION% -r osx-x64 -o out\osx-x64


    7z a -mx=9 -mfb=258 -mpass=15 ArchiSteamFarm\out\ASF-generic.zip %APPVEYOR_BUILD_FOLDER%\ArchiSteamFarm\out\generic\*

    7z a -mx=9 -mfb=258 -mpass=15 ArchiSteamFarm\out\ASF-win-x64.zip %APPVEYOR_BUILD_FOLDER%\ArchiSteamFarm\out\win-x64\*

    7z a -mx=9 -mfb=258 -mpass=15 ArchiSteamFarm\out\ASF-linux-x64.zip %APPVEYOR_BUILD_FOLDER%\ArchiSteamFarm\out\linux-x64\*

    7z a -mx=9 -mfb=258 -mpass=15 ArchiSteamFarm\out\ASF-osx-x64.zip %APPVEYOR_BUILD_FOLDER%\ArchiSteamFarm\out\osx-x64\*
artifacts:
- path: ArchiSteamFarm\out\ASF-generic.zip
  name: ASF-generic.zip
- path: ArchiSteamFarm\out\ASF-win-x64.zip
  name: ASF-win-x64.zip
- path: ArchiSteamFarm\out\ASF-linux-x64.zip
  name: ASF-linux-x64.zip
- path: ArchiSteamFarm\out\ASF-osx-x64.zip
  name: ASF-osx-x64.zip
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: ArchiSteamFarm V$(appveyor_repo_tag_name)
  description: '**NOTICE:** Pre-releases are experimental versions that often contain unpatched bugs, work-in-progress features or rewritten implementations. If you don''t consider yourself advanced user, please download **[latest stable release](https://github.com/JustArchi/ArchiSteamFarm/releases/latest)** instead. Pre-release versions are dedicated to users who know how to report bugs, deal with issues and give feedback - no technical support will be given. Check out ASF **[release cycle](https://github.com/JustArchi/ArchiSteamFarm/wiki/Release-cycle)** if you''d like to learn more.\n\n---\n\nThis is automated AppVeyor GitHub deployment, human-readable changelog should be available soon. In the meantime please refer to **[GitHub commits](https://github.com/JustArchi/ArchiSteamFarm/commits/$(appveyor_repo_tag_name))**.\n\n---\n\nASF is available for free. If you''re grateful for what we''re doing, please consider donating. Developing ASF requires massive amount of time and knowledge, especially when it comes to Steam (and its problems). Even 1$ is highly appreciated and shows that you care!\n\n [![Patreon support](https://img.shields.io/badge/Patreon-support-yellow.svg)](https://www.patreon.com/JustArchi) [![Paypal.me donate](https://img.shields.io/badge/Paypal.me-donate-yellow.svg)](https://www.paypal.me/JustArchi/1usd) [![Paypal donate](https://img.shields.io/badge/Paypal-donate-yellow.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HD2P2P3WGS5Y4) [![Bitcoin donate](https://img.shields.io/badge/Bitcoin-donate-yellow.svg)](https://blockchain.info/payment_request?address=1Archi6M1r5b41Rvn1SY2FfJAzsrEUT7aT) [![Steam donate](https://img.shields.io/badge/Steam-donate-yellow.svg)](https://steamcommunity.com/tradeoffer/new/?partner=46697991&token=0ix2Ruv_)'
  auth_token:
    secure: QC5gIDMvSpd43EG6qW8d1E3ZHiVU4aR7pbKQonXstjj/JtAABf5S1IbtoY4OsnOR
  artifact: /.*/
  draft: true
  prerelease: true
  force_update: false
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/6982e3cd9dc9e57b1119
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true